// quotes.js

const quotesData = [
    { title: "Inspiration", quote: "This is an inspiring quote." },
    { title: "Motivation", quote: "Stay motivated and keep moving forward." },
    { title: "Success", quote: "Success is not final, failure is not fatal: It is the courage to continue that counts." },
    { title: "Dreams", quote: "The future belongs to those who believe in the beauty of their dreams." },
    { title: "Wisdom", quote: "The only true wisdom is in knowing you know nothing." },
    { title: "Courage", quote: "Courage is not the absence of fear, but the triumph over it." },
    { title: "Love", quote: "Love is composed of a single soul inhabiting two bodies." },
    { title: "Hope", quote: "Hope is being able to see that there is light despite all of the darkness." },
    { title: "Imagination", quote: "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world." },
    { title: "Strength", quote: "Strength does not come from physical capacity. It comes from an indomitable will." },
    { title: "Kindness", quote: "No act of kindness, no matter how small, is ever wasted." },
    { title: "Perseverance", quote: "Perseverance is failing 19 times and succeeding the 20th." },
    { title: "Gratitude", quote: "Gratitude turns what we have into enough." },
    { title: "Leadership", quote: "Leadership is not about being in charge. It's about taking care of those in your charge." },
    { title: "Happiness", quote: "Happiness is not something ready-made. It comes from your own actions." },
    { title: "Friendship", quote: "Friendship is born at that moment when one person says to another: 'What! You too? I thought I was the only one.'" },
    { title: "Change", quote: "The only way to make sense out of change is to plunge into it, move with it, and join the dance." },
    { title: "Adventure", quote: "Life is either a daring adventure or nothing at all." },
    { title: "Creativity", quote: "Creativity is intelligence having fun." },
    { title: "Faith", quote: "Faith is taking the first step even when you don't see the whole staircase." },
    { title: "Patience", quote: "Patience is not the ability to wait, but the ability to keep a good attitude while waiting." },
    { title: "Humility", quote: "True humility is not thinking less of yourself; it is thinking of yourself less." },
    { title: "Integrity", quote: "Real integrity is doing the right thing, knowing that nobody's going to know whether you did it or not." },
    { title: "Peace", quote: "Peace begins with a smile." },
    { title: "Purpose", quote: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well." },
    { title: "Excellence", quote: "Excellence is not a skill, it's an attitude." },
    { title: "Forgiveness", quote: "Forgiveness is the fragrance that the violet sheds on the heel that has crushed it." },
    { title: "Wisdom", quote: "Knowing yourself is the beginning of all wisdom." },
    { title: "Adversity", quote: "Adversity has the effect of eliciting talents which, in prosperous circumstances, would have lain dormant." },
    { title: "Optimism", quote: "The pessimist complains about the wind; the optimist expects it to change; the realist adjusts the sails." },
    { title: "Resilience", quote: "The human capacity for burden is like bamboo - far more flexible than you'd ever believe at first glance." },
    { title: "Kindness", quote: "Kindness is a language which the deaf can hear and the blind can see." },
    { title: "Innovation", quote: "Innovation distinguishes between a leader and a follower." },
    { title: "Generosity", quote: "No one has ever become poor by giving." },
    { title: "Equality", quote: "I have a dream that one day this nation will rise up and live out the true meaning of its creed: 'We hold these truths to be self-evident, that all men are created equal.'" },
    { title: "Education", quote: "Education is the most powerful weapon which you can use to change the world." },
    { title: "Justice", quote: "Injustice anywhere is a threat to justice everywhere." },
    { title: "Courage", quote: "It takes courage to grow up and become who you really are." },
    { title: "Empathy", quote: "You never really understand a person until you consider things from his point of view... Until you climb inside of his skin and walk around in it." },
    { title: "Truth", quote: "The truth will set you free." },
    { title: "Gratitude", quote: "Gratitude is not only the greatest of virtues, but the parent of all the others." },
    { title: "Humor", quote: "Against the assault of laughter, nothing can stand." },
    { title: "Optimism", quote: "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence." },
    { title: "Compassion", quote: "If you want others to be happy, practice compassion. If you want to be happy, practice compassion." },
    { title: "Friendship", quote: "A friend is someone who knows all about you and still loves you." },
    { title: "Persistence", quote: "Persistence and determination alone are omnipotent. The slogan 'press on' has solved and always will solve the problems of the human race." },
    { title: "Curiosity", quote: "The important thing is not to stop questioning. Curiosity has its own reason for existing." },
    { title: "Self-discipline", quote: "I count him braver who overcomes his desires than him who conquers his enemies; for the hardest victory is over self." },
    { title: "Hope", quote: "Hope is the thing with feathers that perches in the soul and sings the tune without the words and never stops at all." },
  ];
  
  export default quotesData;
  